--category table creation
create table PRcategory (
category_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
category_name VARCHAR2(50) NOT NULL UNIQUE
);
--Inserting data into category table
INSERT INTO PRcategory (category_name) values ('knives');
INSERT INTO PRcategory (category_name) values ('flatwares');
INSERT INTO PRcategory (category_name) values ('cookwares');
INSERT INTO PRcategory (category_name) values ('electronics');
INSERT INTO PRcategory (category_name) values ('graters');
INSERT INTO PRcategory (category_name) values ('sport bottles');
INSERT INTO PRcategory (category_name) values ('glasswares');
INSERT INTO PRcategory (category_name) values ('appliances');
INSERT INTO PRcategory (category_name) values ('gadgets');
INSERT INTO PRcategory (category_name) values ('food store');
INSERT INTO PRcategory (category_name) values ('bath');
INSERT INTO PRcategory (category_name) values ('pantryware');
INSERT INTO PRcategory (category_name) values ('bakeware');
INSERT INTO PRcategory (category_name) values ('storage');
INSERT INTO PRcategory (category_name) values ('miscellaneous');
INSERT INTO PRcategory (category_name) values ('kitchen textiles');
INSERT INTO PRcategory (category_name) values ('cleaning tools');
INSERT INTO PRcategory (category_name) values ('tea/ coffee');
INSERT INTO PRcategory (category_name) values ('ceramics');
INSERT INTO PRcategory (category_name) values ('seasonal');
INSERT INTO PRcategory (category_name) values ('decorators');
INSERT INTO PRcategory (category_name) values ('rugs');
INSERT INTO PRcategory (category_name) values ('candles');
INSERT INTO PRcategory (category_name) values ('therawell');
INSERT INTO PRcategory (category_name) values ('lunchbox');
INSERT INTO PRcategory (category_name) values ('jwellery');
INSERT INTO PRcategory (category_name) values ('bulk');


--supplier table creation
CREATE TABLE PRsupplier(
supplier_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
supplier_name VARCHAR2(50) NOT NULL,
supplier_phone VARCHAR2(10) NOT NULL UNIQUE,
supplier_email varchar2(50) NOT NULL UNIQUE
);
--Inserting data into supplier table
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Canada Goods Inc.','6471112222','cgoods@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Canada Kitchens Inc.','6472223333','ckitchens@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Ontario Goods Inc.','6473334444','ogoods@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Ontario Kitchens Inc.','6474445555','okitchens@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Toronto Goods Inc.','6475556666','tgoods@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Toronto Kitchens Inc.','6476667777','tkitchens@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Eat well Suppliers','6477778888','eatwell@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Sleep well suppliers','6478889999','sleepwell@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Canada Homes','6479990000','chomes@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('American Kitchen Inc.','6470001111','akitchen@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('China to Canada Goods Inc.','6471113333','c2c@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Multiple brands suppliers Inc.','6473335555','mbrands@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Great suppliers Inc.','6475557777','greatsuppliers@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Kitchen king Inc.','6477779999','kitchenking@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Ontario wellness Inc.','6479992222','owelness@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Maple leaf Inc.','6472224444','mapleleaf@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Home hardware Inc.','6474446666','homehardware@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Kitchen basics Inc.','6476668888','kbasics@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Cookwell Inc.','6478880000','cwell@gmail.com');
INSERT INTO PRsupplier (supplier_name,supplier_phone,supplier_email) values ('Dream big Inc.','6470001234','dreambig@gmail.com');



--location table creation
CREATE TABLE PRlocation (
location_id NUMBER(5) PRIMARY KEY,
aisle_number NUMBER(3) NOT NULL,
bay_number NUMBER(3) NOT NULL
);

--Inserting data into location
INSERT ALL
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10011,1,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10012,1,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10013,1,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10014,1,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10015,1,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10016,1,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10017,1,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10018,1,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (10019,1,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20021,2,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20022,2,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20023,2,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20024,2,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20025,2,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20026,2,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20027,2,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20028,2,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (20029,2,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30031,3,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30032,3,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30033,3,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30034,3,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30035,3,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30036,3,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30037,3,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30038,3,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (30039,3,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40041,4,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40042,4,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40043,4,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40044,4,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40045,4,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40046,4,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40047,4,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40048,4,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (40049,4,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50051,5,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50052,5,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50053,5,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50054,5,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50055,5,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50056,5,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50057,5,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50058,5,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (50059,5,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60061,6,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60062,6,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60063,6,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60064,6,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60065,6,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60066,6,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60067,6,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60068,6,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (60069,6,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70071,7,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70072,7,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70073,7,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70074,7,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70075,7,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70076,7,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70077,7,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70078,7,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (70079,7,9)

INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80031,8,1)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80032,8,2)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80033,8,3)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80034,8,4)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80035,8,5)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80036,8,6)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80037,8,7)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80038,8,8)
INTO PRlocation (location_id,aisle_number,bay_number) VALUES (80039,8,9)
select * from dual

--category table creation
CREATE TABLE PRproduct (
product_id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
category_id NUMBER(5),
supplier_id NUMBER(5),
product_description varchar2(100),
stock number(4),
upc CHAR(10) UNIQUE,
vin CHAR(5) UNIQUE
);
ALTER TABLE PRproduct 
ADD CONSTRAINT PRproduct_category_id_fk
FOREIGN KEY (category_id) REFERENCES PRcategory(category_id);
ALTER TABLE PRproduct
ADD CONSTRAINT PRproduct_supplier_id_fk
FOREIGN KEY (supplier_id) REFERENCES PRsupplier(supplier_id);


INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (1,1,'Henckles 14\" bread knife-silver',20,6446911515,55425);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (2,2,'Alpia spoon set-silver',20,1601332865,42264);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (3,3,'Lodge pro logic cast iron grill pan dia 10" black',0,2661637758,64428);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (4,4,'Polaroid Noise Isolating ear buds- blue',12,6100959320,47369);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (5,5,'Libbey Hamlet Cosmo Glasses - Set of 4',13,4857418709,19688);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (6,6,'Breville Mini Smart Toaster Oven',14,2629136015,44761);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (7,7,'Joie multicolor spoon rest',15,7533217405,31279);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (8,8,'Danesco wireworks bread basket',1,9115409014,20093);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (9,9,'Splash mini shower caddy',2,8798035096,65888);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (10,10,'Fox Run Mini Springform Pan',4,1220381278,58077);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (11,11,'Copco Non-Skid Cabinet Organizer',6,4486378966,60745);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (12,12,'Goodbrand multicolor ice packs',7,3804820477,43008);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (13,13,'Grimm Phrase Bossy Apron (Pink)',8,1861068707,54868);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (14,14,'Casabella Wayclean Magnet Microfiber Squeeze Mop (Grey/Green)',66,2178852815,58057);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (15,15,'Boston Warehouse Flea Market Bird House Ceramic Mug (Multi Colour)',55,6477017844,34476);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (16,16,'Sharper Image Colour Changing 16-Clothespins LED Clip String Lights (Clear)',45,8658189952,76315);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (17,17,'Empire Tuscany Eucalyptus Mint 3-Wick Glass Jar Candle',43,2584791172,75480);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (18,18,'Upper Canada Therawell Anti-Stress Wire Head Massager (Lavender)',90,1991105102,23623);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (19,19,'Umbra Zoola Die-Cast Zinc Elephant Ring Holder (Brass)',100,3725390956,10320);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (20,20,'5 seat outdoor seating set',500,9979465740,92853);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (21,1,'Microplane Premium 12" Rasp Grater & Zester (Eggplant)',1234,2232557192,24817);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (22,2,'Thermos Licensed Pj Masks Funtainer Sport Bottle with Straw (Blue)',2345,6064397178,53098);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (23,3,'iDesign Linus Pantry Organizer - Turntable',122,9647831618,54255);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (24,4,'Le Cuistot Vieille France Mortar & Pestle - Blue',6,2682750655,42314);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (25,5,'Outset BBQ Square Grill Basket (Chrome)',8,7569691587,25984);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (26,6,'Contact Grip Prints Lunchbox Shelf-Drawer Liner (Multi Colour)',4,9126132489,91677);
INSERT INTO PRproduct (category_id,supplier_id,product_description,stock,upc,vin) values (27,7,'herman large rugs',0,9849930029,12659);

-creating intermediate table product_location
CREATE TABLE PRproduct_location(
product_id NUMBER(5),
location_id NUMBER(5)
);
--implementing constraints
ALTER TABLE PRproduct_location 
ADD CONSTRAINT PRoduct_location_pr_id_fk
FOREIGN KEY (product_id) REFERENCES PRproduct(product_id);
ALTER TABLE PRproduct_location 
ADD CONSTRAINT PRoduct_location_id_fk
FOREIGN KEY (location_id) REFERENCES PRlocation(location_id);

--inserting data into product_location table
INSERT ALL
INTO PRproduct_location (product_id,location_id) VALUES (1,10011)
INTO PRproduct_location (product_id,location_id) VALUES (2,10012)
INTO PRproduct_location (product_id,location_id) VALUES (3,30031)
INTO PRproduct_location (product_id,location_id) VALUES (4,40041)
INTO PRproduct_location (product_id,location_id) VALUES (5,50051)
INTO PRproduct_location (product_id,location_id) VALUES (6,60061)
INTO PRproduct_location (product_id,location_id) VALUES (7,10012)
INTO PRproduct_location (product_id,location_id) VALUES (8,20022)
INTO PRproduct_location (product_id,location_id) VALUES (9,30033)
INTO PRproduct_location (product_id,location_id) VALUES (10,40044)
INTO PRproduct_location (product_id,location_id) VALUES (11,50055)
INTO PRproduct_location (product_id,location_id) VALUES (12,10013)
INTO PRproduct_location (product_id,location_id) VALUES (13,20023)
INTO PRproduct_location (product_id,location_id) VALUES (14,30033)
INTO PRproduct_location (product_id,location_id) VALUES (15,40044)
INTO PRproduct_location (product_id,location_id) VALUES (16,50055)
INTO PRproduct_location (product_id,location_id) VALUES (17,60065)
INTO PRproduct_location (product_id,location_id) VALUES (21,10014)
INTO PRproduct_location (product_id,location_id) VALUES (22,20024)
INTO PRproduct_location (product_id,location_id) VALUES (23,30034)
INTO PRproduct_location (product_id,location_id) VALUES (24,40044)
INTO PRproduct_location (product_id,location_id) VALUES (25,50055)
INTO PRproduct_location (product_id,location_id) VALUES (26,10015)
INTO PRproduct_location (product_id,location_id) VALUES (27,20025)
INTO PRproduct_location (product_id,location_id) VALUES (2,30035)
INTO PRproduct_location (product_id,location_id) VALUES (4,40045)
INTO PRproduct_location (product_id,location_id) VALUES (6,50055)
INTO PRproduct_location (product_id,location_id) VALUES (1,60065)
INTO PRproduct_location (product_id,location_id) VALUES (6,10016)
INTO PRproduct_location (product_id,location_id) VALUES (1,20026)
INTO PRproduct_location (product_id,location_id) VALUES (9,30036)
INTO PRproduct_location (product_id,location_id) VALUES (1,40046)
INTO PRproduct_location (product_id,location_id) VALUES (27,50056)
INTO PRproduct_location (product_id,location_id) VALUES (1,10017)
INTO PRproduct_location (product_id,location_id) VALUES (9,20027)
INTO PRproduct_location (product_id,location_id) VALUES (1,30037)
INTO PRproduct_location (product_id,location_id) VALUES (5,40047)
INTO PRproduct_location (product_id,location_id) VALUES (1,50057)
INTO PRproduct_location (product_id,location_id) VALUES (4,10018)
INTO PRproduct_location (product_id,location_id) VALUES (1,20028)
INTO PRproduct_location (product_id,location_id) VALUES (1,30038)
INTO PRproduct_location (product_id,location_id) VALUES (1,40048)
INTO PRproduct_location (product_id,location_id) VALUES (6,50058)
INTO PRproduct_location (product_id,location_id) VALUES (1,10019)
INTO PRproduct_location (product_id,location_id) VALUES (7,20029)
INTO PRproduct_location (product_id,location_id) VALUES (1,30039)
INTO PRproduct_location (product_id,location_id) VALUES (3,40049)
INTO PRproduct_location (product_id,location_id) VALUES (1,50059)
SELECT * FROM dual;

--table creation: employee
CREATE TABLE PRemployee(
employee_id CHAR(4) PRIMARY KEY,
first_name VARCHAR2(25) NOT NULL,
last_name VARCHAR2(25) NOT NULL,
street VARCHAR2(50) NOT NULL,
city VARCHAR2(50) NOT NULL,
phone_number CHAR(10) NOT NULL,
email VARCHAR2(50) NOT NULL
)
--data insertion
INSERT ALL 
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1001','Subarna','Khadka','240 Wellesley St. E','Toronto','4679140000','skhadka@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1002','Jarod','Rezei','241 Wellesley St. E','Regina','4679140001','JRezei@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1003','Tran','jjs','242 Wellesley St. E','Toronto','4679140002','Tj@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1004','Wang','Lu','243 Wellesley St. E','Toronto','4679140003','Wlui@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1005','Ramesh','Kumar','244 Wellesley St. E','Toronto','4679140004','RKumar@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1006','Tshering','Dolma','245 Wellesley St. E','Toronto','4679140005','tdolma@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1007','Trent','Minia','246 Wellesley St. E','Toronto','4679140006','Tminia@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1008','Micheal','Assymota','247 Wellesley St. E','Toronto','4679140007','Ma@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1009','Joyeeta','Nandi','248 Wellesley St. E','Toronto','4679140008','JNandi@gmail.com')
INTO PRemployee (employee_id,first_name,last_name,street, city, phone_number,email) values ('1010','Ismail','Khan','249 Wellesley St. E','Toronto','4679140009','Ikhan@gmail.com')
SELECT * FROM dual;

--table creation: purchase_order
CREATE TABLE PRpurchase_order(
po_id CHAR(4) PRIMARY KEY,
receiver_id CHAR(4),
total_cost NUMBER(5)
)
--implementing constraints
ALTER TABLE PRpurchase_order
ADD CONSTRAINT P_o_receiver_id_fk
FOREIGN KEY (receiver_id) REFERENCES PRemployee(employee_id)

--data insersion in table purchase_order
INSERT ALL 
INTO PRpurchase_order (po_id,receiver_id) VALUES ('1010',1001)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('2020',1002)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('3030',1003)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('4040',1004)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('5050',1005)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('6060',1006)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('7070',1007)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('8080',1008)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('9090',1009)
INTO PRpurchase_order (po_id,receiver_id) VALUES ('1011',1010)
SELECT * FROM dual;



--table creation: purchase_order_items
CREATE TABLE PRpurchase_order_items(
product_id NUMBER(5),
po_id CHAR(4),
cost NUMBER(5),
quantity NUMBER(4)
)
--implementing constraints
ALTER TABLE PRpurchase_order_items
ADD CONSTRAINT p_o_items_product_id_fk
FOREIGN KEY (product_id) REFERENCES PRproduct(product_id)

ALTER TABLE PRpurchase_order_items
ADD CONSTRAINT p_o_items_po_id_fk
FOREIGN KEY (po_id) REFERENCES PRpurchase_order(po_id)

--data insertion in purchase_order_items
INSERT ALL 
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (1,1010,20,9)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (5,1011,40,12)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (26,2020,200,23)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (15,3030,90,34)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (27,4040,95,45)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (7,5050,109,56)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (17,6060,34,67)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (8,7070,5,3)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (21,8080,66,23)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (9,9090,77,78)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (22,1010,88,100)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (10,2020,11,6)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (23,3030,55,75)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (11,4040,88,144)
INTO PRpurchase_order_items (product_id,po_id,cost,quantity) values (24,9090,99,72)
SELECT * FROM dual;

--table creation PRcustomer
CREATE TABLE PRcustomer(
customer_id CHAR(4) PRIMARY KEY,
first_name VARCHAR2(25) NOT NULL,
last_name VARCHAR2(25) NOT NULL,
street VARCHAR2(50) NOT NULL,
city VARCHAR2(50) NOT NULL,
phone_number CHAR(10) NOT NULL,
email VARCHAR2(50) NOT NULL
)


--data insersion in PRcustomer table
INSERT ALL 
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1001','Santosh','Khadka','240 Wellesley St. E','Toronto','4679140000','skhadka@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1002','Shereen','Jaz','241 Wellesley St. E','Regina','4679140001','JRezei@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1003','Ting','Tu','242 Wellesley St. E','Toronto','4679140002','Tj@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1004','Shahrukh','Khan','243 Wellesley St. E','Toronto','4679140003','Wlui@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1005','Akshya','Kumar','244 Wellesley St. E','Toronto','4679140004','RKumar@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1006','Dolce','Gabbana','245 Wellesley St. E','Toronto','4679140005','tdolma@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1007','Samsung','iphone','246 Wellesley St. E','Toronto','4679140006','Tminia@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1008','Mic','Mota','247 Wellesley St. E','Toronto','4679140007','Ma@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1009','Jta','Ndi','248 Wellesley St. E','Toronto','4679140008','JNandi@gmail.com')
INTO PRcustomer (customer_id,first_name,last_name,street, city, phone_number,email) values ('1010','Ism','khn','249 Wellesley St. E','Toronto','4679140009','Ikhan@gmail.com')
SELECT * FROM dual;

--order table creation
CREATE TABLE PRorder(
order_id CHAR(4) PRIMARY KEY,
customer_id CHAR(4),
packer_id CHAR(4),
total_price NUMBER(5)
)
--implementing constraints
ALTER TABLE PRorder 
ADD CONSTRAINT PROrder_cust_id_fk
FOREIGN KEY(customer_id) REFERENCES PRcustomer(customer_id);

ALTER TABLE PRorder 
ADD CONSTRAINT PROrder_packer_id_fk
FOREIGN KEY(packer_id) REFERENCES PRemployee(employee_id);

--data insersion in PRorder table
INSERT ALL 
INTO PRorder (order_id,customer_id,packer_id) VALUES ('1010','1001','1010')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('2020','1002','1009')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('3030','1003','1008')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('4040','1004','1007')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('5050','1005','1006')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('6060','1006','1005')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('7070','1007','1004')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('8080','1008','1003')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('9090','1009','1002')
INTO PRorder (order_id,customer_id,packer_id) VALUES ('1011','1010','1001')
SELECT * FROM dual;
select order_id from PRorder order by order_id


--table creation PRorder_items
CREATE TABLE PRorder_items(
product_id NUMBER(5),
order_id CHAR(4),
price NUMBER(5),
quantity NUMBER(4))

--foreign key constraints definition
ALTER TABLE PRorder_items 
ADD CONSTRAINT PRO_items_product_id_fk
FOREIGN KEY(product_id) REFERENCES PRproduct(product_id)

ALTER TABLE PRorder_items 
ADD CONSTRAINT PRO_items_order_id_fk
FOREIGN KEY(order_id) REFERENCES PRorder(order_id)


--PRorder_items table data insersion
INSERT ALL 
INTO PRorder_items (product_id,order_id,price,quantity) values (1,1010,22,8)
INTO PRorder_items (product_id,order_id,price,quantity) values (5,1011,43,2)
INTO PRorder_items (product_id,order_id,price,quantity) values (26,2020,210,5)
INTO PRorder_items (product_id,order_id,price,quantity) values (15,3030,100,6)
INTO PRorder_items (product_id,order_id,price,quantity) values (27,4040,100,7)
INTO PRorder_items (product_id,order_id,price,quantity) values (7,5050,110,8)
INTO PRorder_items (product_id,order_id,price,quantity) values (17,6060,35,4)
INTO PRorder_items (product_id,order_id,price,quantity) values (8,7070,8,1)
INTO PRorder_items (product_id,order_id,price,quantity) values (21,8080,70,1)
INTO PRorder_items (product_id,order_id,price,quantity) values (9,9090,80,20)
INTO PRorder_items (product_id,order_id,price,quantity) values (22,1010,90,10)
INTO PRorder_items (product_id,order_id,price,quantity) values (10,2020,15,5)
INTO PRorder_items (product_id,order_id,price,quantity) values (23,3030,58,45)
INTO PRorder_items (product_id,order_id,price,quantity) values (11,4040,90,110)
INTO PRorder_items (product_id,order_id,price,quantity) values (24,9090,100,72)
SELECT * FROM dual;

--table creation: PRshipper
CREATE TABLE PRshipper(
shipper_id CHAR(5) PRIMARY KEY,
shipper_name VARCHAR2(50),
phone CHAR(10),
email VARCHAR2(50)
)

--data insersion in PRshipper table
INSERT ALL 
INTO PRshipper (shipper_id,shipper_name,phone,email) values ('10001','CanPost Inc.','6479870000','canpost@shipper.com')
INTO PRshipper (shipper_id,shipper_name,phone,email) values ('10002','Puro Ltd.','6479870001','puro@shipper.com')
INTO PRshipper (shipper_id,shipper_name,phone,email) values ('10003','Fedax Inc.','6479870002','fedax@shipper.com')
INTO PRshipper (shipper_id,shipper_name,phone,email) values ('10004','DHal Ltd.','6479870003','dhal@shipper.com')
INTO PRshipper (shipper_id,shipper_name,phone,email) values ('10005','Easy Shippers','6479870004','eship@shipper.com')
SELECT * FROM dual;

--table creation: PRshipping
CREATE TABLE PRshipping(
tracking_number CHAR(10) PRIMARY KEY,
order_id CHAR(4),
shipper_id CHAR(5),
ship_status CHAR(1) DEFAULT '0'
)
--defining constraints
ALTER TABLE PRshipping 
ADD CONSTRAINT  PRshipping_shipStat_ck
CHECK (ship_status in ( '1', '0' ));


ALTER TABLE PRshipping 
ADD CONSTRAINT PRshipping_ord_id_fk
FOREIGN KEY(order_id) REFERENCES PRorder(order_id)


ALTER TABLE PRshipping 
ADD CONSTRAINT PRshipping_shipper_id_fk
FOREIGN KEY(shipper_id) REFERENCES PRshipper(shipper_id)
select * from PRshipper


tracking_number CHAR(10) PRIMARY KEY,
order_id CHAR(4),
shipper_id CHAR(5),
ship_status CHAR(1) DEFAULT '0'
--PRshipping data insersion
INSERT ALL 
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (1010101010,1010,10005,1)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (2020202020,1011,10004,1)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (3030303030,2020,10004,0)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (4040404040,7070,10002,0)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (5050505050,3030,10001,0)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (6060606060,9090,10001,0)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (7070707070,8080,10001,0)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (8080808080,1010,10004,1)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (9090909090,9090,10002,1)
INTO PRshipping (tracking_number,order_id,shipper_id,ship_status) VALUES (1011101110,1011,10005,1)
SELECT * FROM dual;



















